# Generated by Django 6.0 on 2026-01-20 15:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Diary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mood",
                    models.IntegerField(
                        choices=[
                            (1, "🙂 Хорошо"),
                            (2, "😀 Отлично"),
                            (3, "🥰 Влюблён"),
                            (4, "😡 Злой"),
                            (5, "😐 Нормально"),
                            (6, "🤔 Задумчивый"),
                            (7, "😢 Грустный"),
                            (8, "😭 Плачу"),
                        ],
                        default=5,
                        verbose_name="Настроение",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
                (
                    "text",
                    models.TextField(
                        blank=True, help_text="Что интересного было сегодня?"
                    ),
                ),
                (
                    "date",
                    models.DateField(auto_now_add=True, verbose_name="Дата записи"),
                ),
                (
                    "image_file",
                    models.ImageField(
                        blank=True,
                        help_text="Изображение для записи",
                        null=True,
                        upload_to="diary_images/%Y/%m/%d/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "music_link",
                    models.URLField(
                        blank=True,
                        help_text="Ссылка на YouTube, Spotify, Яндекс.Музыку, VK музыка",
                        validators=[django.core.validators.URLValidator()],
                        verbose_name="Ссылка на музыку",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diaries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись личного дневника",
                "verbose_name_plural": "Записи личного дневника",
                "ordering": ["-created_at"],
            },
        ),
    ]
