# Generated by Django 6.0 on 2026-01-22 17:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diary",
            name="date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Дата записи"
            ),
        ),
    ]
